[package]
name = "nav_e_ffi"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "staticlib"]

[dependencies]
nav_engine = { path = "../nav_engine" }
flutter_rust_bridge = "=2.11.1"
anyhow = "1"
